### PR TITLE
Releng add more category update site

### PR DESCRIPTION
**Pull request by aliakar82**

### CODE REVIEW

**Comment by minhtutonthat** [comment]
Yes, I don't see either why we need a SDK feature. To be coherent with other add-ons, could we have one normal feature, one source feature, one collaboration feature and one test feature (if needed)?

**Comment by aliakar82** [comment]
We need to have only one feature including the sources which appears in the update site and not two separate features. Have a look on CYBERSECU-41.
And below what Shyam wrote in his email:
For open source add-ons
•      1 category for add-on (source (i.e no separate category for non-source))
•      2 category for add-on collaboration (do mention collaboration instead of CDO)

**Comment by minhtutonthat** [comment]
OK Ali. To be coherent with other add-ons, I've commited to:
- Fix the Jenkins file to launch the job in multibranch pipeline
- Add test feature in update site
- Have only the source feature in update site

**Comment by minhtutonthat** [comment]
Replaced by https://github.com/eclipse/capella-cybersecurity/pull/11

**Pull request closed without merging**
